Update python-package-conda.yml

diff --git a/.github/workflows/python-package-conda.yml b/.github/workflows/python-package-conda.yml
--- a/.github/workflows/python-package-conda.yml
+++ b/.github/workflows/python-package-conda.yml
@@ -4,14 +4,20 @@ on:
   push:
     branches:
       - main
+  pull_request:
+    branches:
+      - main
 
 jobs:
-  docker-build-and-push:
+  build:
     runs-on: ubuntu-latest
 
     steps:
     - name: Check out the repository
       uses: actions/checkout@v2
+
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v2
 
     - name: Log in to DockerHub
       uses: docker/login-action@v2
@@ -19,9 +25,16 @@ jobs:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
 
+    - name: Verify Dockerfile Path
+      run: |
+        if [ ! -f ./app/docker/Dockerfile ]; then
+          echo "ERROR: Dockerfile not found at ./app/docker/Dockerfile. Please check the path.";
+          exit 1;
+        fi
+
     - name: Build Docker image
       run: |
-        docker build . --file ./docker/Dockerfile --tag swimpyblaq/chima:latest
+        docker build . --file ./app/docker/Dockerfile --tag swimpyblaq/chima:latest
 
     - name: Push Docker image to DockerHub
       run: |
